from __future__ import annotations

from project.ui._streamlit import get_streamlit


SECTION_OPTIONS = ("📋 Trade Ideas", "💼 Positions", "📊 Reports")


def render(repository) -> None:
    st = get_streamlit()
    st.title("Trading")
    st.caption("Choose a section to load only the data you need.")
    section = _section_selector(st)
    if section == SECTION_OPTIONS[0]:
        _render_trade_ideas(repository, st)
    elif section == SECTION_OPTIONS[1]:
        _render_positions(repository, st)
    else:
        _render_reports(repository, st)


def _section_selector(st) -> str:
    current = getattr(st, "session_state", {}).get(
        "trading_section",
        SECTION_OPTIONS[0],
    )
    selectbox = getattr(st, "selectbox", None)
    if not callable(selectbox):
        return current if current in SECTION_OPTIONS else SECTION_OPTIONS[0]
    index = SECTION_OPTIONS.index(current) if current in SECTION_OPTIONS else 0
    try:
        selected = selectbox(
            "Section",
            SECTION_OPTIONS,
            index=index,
            key="trading_section",
        )
    except TypeError:
        selected = selectbox("Section", SECTION_OPTIONS, index=index)
    session_state = getattr(st, "session_state", None)
    if isinstance(session_state, dict):
        session_state["trading_section"] = selected
    return selected


def _load_asset_map(repository):
    return {a.asset_id: a for a in repository.list_assets()}


def _render_trade_ideas(repository, st) -> None:
    st.markdown("<h2>Trade Ideas</h2>", unsafe_allow_html=True)
    ideas = _fetch_trade_ideas(repository)
    open_ideas = _fetch_open_ideas(repository)

    cols = st.columns(3)
    _kpi(cols[0], "Total Ideas", str(len(ideas)))
    _kpi(cols[1], "Open", str(len(open_ideas)), "action" if open_ideas else "ok")
    _kpi(cols[2], "Reviewed", str(len(ideas) - len(open_ideas)))

    if open_ideas:
        st.markdown('<div style="margin-top: 1rem;"></div>', unsafe_allow_html=True)
        st.dataframe(open_ideas, use_container_width=True)
    else:
        st.info("No open trade ideas awaiting review.")
        if ideas:
            with st.expander("All Trade Ideas", expanded=False):
                st.dataframe(ideas, use_container_width=True)
        else:
            _help_box(
                st,
                [
                    "Trade ideas are generated by research "
                    "when hypotheses are evaluated.",
                    "Run research to generate trade ideas: `mft research run`",
                    "Once ideas exist, you can approve, reject, or watch them here.",
                ],
            )


def _render_positions(repository, st) -> None:
    st.markdown("<h2>Positions</h2>", unsafe_allow_html=True)
    positions = _fetch_positions(repository)

    if positions:
        open_count = sum(1 for p in positions if p["Status"] == "open")
        closed_count = sum(1 for p in positions if p["Status"] == "closed")
        pnl_values = [
            float(p["PnL"])
            for p in positions
            if p["PnL"] not in ("-", "")
        ]
        total_pnl = sum(pnl_values)
        cols = st.columns(4)
        _kpi(cols[0], "Total", str(len(positions)))
        _kpi(cols[1], "Open", str(open_count), "action" if open_count else "ok")
        _kpi(cols[2], "Closed", str(closed_count))
        _kpi(
            cols[3],
            "Realized PnL",
            f"{total_pnl:+.2f}",
            "ok" if total_pnl >= 0 else "warning",
        )
        st.markdown('<div style="margin-top: 1rem;"></div>', unsafe_allow_html=True)
        st.dataframe(positions, use_container_width=True)
    else:
        st.info("No positions yet. Approved trade ideas will appear here.")
        _help_box(
            st,
            [
                "**Workflow:** Trade Idea → Approve → Open Position → Close → PnL",
                "Approve a trade idea in the **Trade Ideas** tab above.",
                "Positions are created automatically upon approval.",
            ],
        )


def _render_reports(repository, st) -> None:
    st.markdown("<h2>Reports</h2>", unsafe_allow_html=True)
    backtests = _fetch_backtests(repository)
    outcomes = _fetch_outcomes(repository)
    cols = st.columns(2)
    with cols[0]:
        _kpi(cols[0], "Backtests", str(len(backtests)))
    with cols[1]:
        _kpi(cols[1], "Trade Outcomes", str(len(outcomes)))
    st.markdown('<div style="margin-top: 1rem;"></div>', unsafe_allow_html=True)
    col1, col2 = st.columns(2)
    with col1:
        if backtests:
            st.markdown(
                '<div class="section-card__title">Backtest Results</div>',
                unsafe_allow_html=True,
            )
            st.dataframe(backtests, use_container_width=True)
        else:
            st.info("No backtest results yet.")
    with col2:
        if outcomes:
            st.markdown(
                '<div class="section-card__title">Trade Outcomes</div>',
                unsafe_allow_html=True,
            )
            st.dataframe(outcomes, use_container_width=True)
        else:
            st.info("No trade outcomes recorded yet.")


def _fetch_trade_ideas(repository):
    try:
        raw = repository.get_trade_ideas()
        assets = _load_asset_map(repository)
        return [
            {
                "Symbol": _sym(assets, t.asset_id),
                "Direction": t.direction,
                "Confidence": f"{t.confidence:.2f}",
                "Timestamp": getattr(t, "timestamp", "") or "",
            }
            for t in raw
        ]
    except Exception:
        return []


def _fetch_open_ideas(repository):
    try:
        raw = repository.get_open_trade_ideas()
        assets = _load_asset_map(repository)
        return [
            {
                "Symbol": _sym(assets, t.asset_id),
                "Direction": t.direction,
                "Confidence": f"{t.confidence:.2f}",
                "Timestamp": getattr(t, "timestamp", "") or "",
            }
            for t in raw
        ]
    except Exception:
        return []


def _fetch_positions(repository):
    try:
        raw = repository.get_positions()
        ideas = {t.trade_id: t for t in repository.get_trade_ideas()}
        assets = _load_asset_map(repository)
        return [
            {
                "Symbol": (
                    _sym(assets, ideas[p.trade_id].asset_id)
                    if p.trade_id in ideas
                    else "?"
                ),
                "Direction": (
                    ideas[p.trade_id].direction if p.trade_id in ideas else "?"
                ),
                "Status": p.status,
                "Entry": f"{p.entry_price:.2f}",
                "Exit": f"{p.exit_price:.2f}" if p.exit_price is not None else "—",
                "PnL": f"{p.pnl:.2f}" if p.pnl is not None else "—",
            }
            for p in raw
        ]
    except Exception:
        return []


def _fetch_backtests(repository):
    try:
        raw = repository.get_backtest_results()
        return [
            {
                "Return": f'{getattr(b, "total_return_pct", 0):.2f}%',
                "Sharpe": f'{getattr(b, "sharpe_ratio", 0):.2f}',
                "Trades": str(getattr(b, "total_trades", 0)),
            }
            for b in raw
        ]
    except Exception:
        return []


def _fetch_outcomes(repository):
    try:
        raw = repository.get_trade_outcomes()
        return [
            {
                "PnL": f'{getattr(o, "pnl", 0):.2f}',
            }
            for o in raw
        ]
    except Exception:
        return []


def _sym(assets, asset_id):
    a = assets.get(asset_id)
    return a.symbol if a else asset_id[:8]


def _kpi(container, label, value, state="ok"):
    with container:
        badge = ""
        if state == "action":
            badge = (
                '<div style="margin-top: 0.2rem;">'
                '<span class="badge badge--info">ACTION NEEDED</span></div>'
            )
        elif state == "warning":
            badge = (
                '<div style="margin-top: 0.2rem;">'
                '<span class="badge badge--warning">ATTENTION</span></div>'
            )
        container.markdown(
            f'<div class="kpi-card">'
            f'<div class="kpi-card__label">{label}</div>'
            f'<div class="kpi-card__value">{value}</div>'
            f"{badge}</div>",
            unsafe_allow_html=True,
        )


def _help_box(st, lines):
    html_lines = "".join(f"<li>{line}</li>" for line in lines)
    with st.expander("How it works", expanded=False):
        st.markdown(
            f'<div style="background: #f8fafc; border-radius: 8px; '
            f'padding: 1rem 1.25rem; font-size: 0.85rem; color: #475569; '
            f'line-height: 1.7;">'
            f"<ol style='margin: 0; padding-left: 1.25rem;'>{html_lines}</ol>"
            f"</div>",
            unsafe_allow_html=True,
        )
